---
title: "Hobo temperature loggers"
author: "jillashey"
date: "2/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Required packages for the below analyses.
```{r}
library(plyr) # plyr needs to be loaded before dplyr
library(dplyr)
library(tidyr)
library(xml2)
library(tidyverse)
library(ggplot2)
library(scales)
library(lubridate)
library(patchwork) # To display 2 charts together
library(hrbrthemes)
library(reshape2)
library(gridExtra)
library(plotrix)
library(Rmisc)
library(lattice)
library(viridis)
library(dygraphs)
library(xts)
library(graphics)
```

Read in temp data 
```{r}
Tank1 <- read.csv("data/Hobo/temp_logger/20210206_Tank1_20444040.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank2 <- read.csv("data/Hobo/temp_logger/20210206_Tank2_20719656.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank2 <- Tank2[1:nrow(Tank1),]
Tank3 <- read.csv("data/Hobo/temp_logger/20210206_Tank3_20946643.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank3 <- Tank3[1:nrow(Tank1),]
Tank4 <- read.csv("data/Hobo/temp_logger/20210206_Tank4_2044042.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank4 <- Tank4[1:nrow(Tank1),]
Tank5 <- read.csv("data/Hobo/temp_logger/20210206_Tank5_20719658.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank5 <- Tank5[1:nrow(Tank1),]
Tank6 <- read.csv("data/Hobo/temp_logger/20210206_Tank6_20444029.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank6 <- Tank6[1:nrow(Tank1),]
Tank7 <- read.csv("data/Hobo/temp_logger/20210206_Tank7_20444032.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank7 <- Tank7[1:nrow(Tank1),]
Tank8 <- read.csv("data/Hobo/temp_logger/20210206_Tank8_20946642.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank8 <- Tank8[1:nrow(Tank1),]
Tank9 <- read.csv("data/Hobo/temp_logger/20210206_Tank9_20719657.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank9 <- Tank9[1:nrow(Tank1),]
Tank10 <- read.csv("data/Hobo/temp_logger/20210206_Tank10_20946645.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank10 <- Tank10[1:nrow(Tank1),]
Tank11 <- read.csv("data/Hobo/temp_logger/20210206_Tank11_20444034.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank11 <- Tank11[1:nrow(Tank1),]
Tank12 <- read.csv("data/Hobo/temp_logger/20210206_Tank12_20946644.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank12 <- Tank12[1:nrow(Tank1),]

# Did not get temp hobo loggers for tanks 15-18 until 1/16/21
# Tank15 <- read.csv("data/Hobo/temp_logger/20210206_Tank15_20987156.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank15 <- Tank15[1:nrow(Tank1),]
# Tank16 <- read.csv("data/Hobo/temp_logger/20210206_Tank16_20987157.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank16 <- Tank16[1:nrow(Tank1),]
# Tank17 <- read.csv("data/Hobo/temp_logger/20210206_Tank17_20987159.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank17 <- Tank17[1:nrow(Tank1),]
# Tank18 <- read.csv("data/Hobo/temp_logger/20210206_Tank18_20987158.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank18 <- Tank18[1:nrow(Tank1),]
```

Bind data together into single dataframe 
```{r}
data <- cbind(Tank1, Tank2$V3, Tank3$V3, Tank4$V3, Tank5$V3, Tank6$V3,
              Tank7$V3, Tank8$V3, Tank9$V3, Tank10$V3, Tank11$V3,
              Tank12$V3)
colnames(data) <- c("Date.Time", "Tank1","Tank2", "Tank3", "Tank4", "Tank5", "Tank6", "Tank7","Tank8", "Tank9", "Tank10", "Tank11", "Tank12")
```

Parse date.time and clean data 
```{r}
data$Date.Time <- parse_date_time(data$Date.Time, "%m/%d/%y %I:%M:%S %p", tz = "EST")
data$Date.Time <- data$Date.Time + hours(5) # add 3 hours
data <- data[13:nrow(data)-6,]
#Save acclimation data to file
temp.acc.data <- data
write.csv(temp.acc.data,file="output/20210206_Acclimation.Temperature_data.csv")
```

Convert to long 
```{r}
temp.acc.data <- pivot_longer(temp.acc.data, cols = Tank1:Tank12, names_to="Tank" )
```

Plot temps
```{r}
Acc.Temps <- ggplot(temp.acc.data, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Tank), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/20210206_AcclimationTemps.pdf", plot = last_plot(), width = 8, height = 4)
```
















#### Subset date.time based on Tank15-18

Clear workspace. 
```{r}
rm(list=ls()) 
```

Read in temp data 
```{r}
Tank15 <- read.csv("data/Hobo/temp_logger/20210206_Tank15_20987156.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]




# Tank15 <- Tank15[1:nrow(Tank1),]
# Tank16 <- read.csv("data/Hobo/temp_logger/20210206_Tank16_20987157.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank16 <- Tank16[1:nrow(Tank1),]
# Tank17 <- read.csv("data/Hobo/temp_logger/20210206_Tank17_20987159.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank17 <- Tank17[1:nrow(Tank1),]
# Tank18 <- read.csv("data/Hobo/temp_logger/20210206_Tank18_20987158.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
# Tank18 <- Tank18[1:nrow(Tank1),]









Tank1 <- read.csv("data/Hobo/temp_logger/20210206_Tank1_20444040.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank2 <- read.csv("data/Hobo/temp_logger/20210206_Tank2_20719656.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank2 <- Tank2[1:nrow(Tank1),]
Tank3 <- read.csv("data/Hobo/temp_logger/20210206_Tank3_20946643.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank3 <- Tank3[1:nrow(Tank1),]
Tank4 <- read.csv("data/Hobo/temp_logger/20210206_Tank4_2044042.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank4 <- Tank4[1:nrow(Tank1),]
Tank5 <- read.csv("data/Hobo/temp_logger/20210206_Tank5_20719658.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank5 <- Tank5[1:nrow(Tank1),]
Tank6 <- read.csv("data/Hobo/temp_logger/20210206_Tank6_20444029.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank6 <- Tank6[1:nrow(Tank1),]
Tank7 <- read.csv("data/Hobo/temp_logger/20210206_Tank7_20444032.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank7 <- Tank7[1:nrow(Tank1),]
Tank8 <- read.csv("data/Hobo/temp_logger/20210206_Tank8_20946642.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank8 <- Tank8[1:nrow(Tank1),]
Tank9 <- read.csv("data/Hobo/temp_logger/20210206_Tank9_20719657.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank9 <- Tank9[1:nrow(Tank1),]
Tank10 <- read.csv("data/Hobo/temp_logger/20210206_Tank10_20946645.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank10 <- Tank10[1:nrow(Tank1),]
Tank11 <- read.csv("data/Hobo/temp_logger/20210206_Tank11_20444034.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank11 <- Tank11[1:nrow(Tank1),]
Tank12 <- read.csv("data/Hobo/temp_logger/20210206_Tank12_20946644.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:3]
Tank12 <- Tank12[1:nrow(Tank1),]
```





