---
title: "Ash free dry weight"
author: "jillashey"
date: "2023-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plyr")) install.packages("plyr")
if (!require("Rmisc")) install.packages("Rmisc")
if (!require("gridExtra")) install.packages("gridExtra")
if (!require("formattable")) install.packages("formattable")
if (!require("data.table")) install.packages("data.table")
if (!require("htmltools")) install.packages("htmltools")
if (!require("webshot")) install.packages("webshot")
if (!require("agricolae")) install.packages("agricolae")
if (!require("sjPlot")) install.packages("sjPlot")
# load packages
library(plyr)
library(dplyr)
library(tidyverse)
library(plotrix)
library(Rmisc)
library(gridExtra)
library(formattable)
library(data.table)
library(htmltools)
library(webshot)
library(agricolae)
library(lme4)
library(car)
library(sjPlot)
```

Dry weight - organic and inorganic compounds 
Ash-free dry weight - organic compounds 

## Read in ash-free dry weight raw data, surface area, homogenate volume and metadata 
```{r}
AFDW <- read.csv("data/Physiology/AFDW.csv", header = T, na.strings = "") %>% filter(!is.na(PlugID)) %>% select(PlugID, Fraction, initial.mass.g, dry.pan.mass.g, burnt.pan.mass.g)

# Load surface area, homogenate volume and master fragment sheet 
surface_area <- read.csv("data/Physiology/SurfaceArea.csv", header = T, na.strings = "") %>% select(PlugID, Area_cm)
homogenate_vol <- read.csv("data/Physiology/homogenate_volume.csv", header = T, na.strings = "") %>% select(PlugID, vol_mL) 
master <- read.csv("data/MasterFragmentSheet.csv", header = T, na.strings = "") %>% filter(Metric == "P/R, molec") %>% select(PlugID, Site, Treatment, Timepoint)

#metadata <- join_all(list(AFDW, surface_area, homogenate_vol, master), by = "PlugID", type = "left")
#metadata$vol_mL <- gsub("NA", "", metadata$vol_mL)
```

## Calculate mass per mL 
```{r}

```







