---
title: "DailyMeasures"
author: "jillashey"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(tidyverse)
```

Check working directory
```{r}
getwd() 
# don't know why its in the scripts folder, need to move
```

# Load data
```{r}
# Load data
daily <- read.csv("../data/DailyMeasurements.csv", header = T)
daily <- daily[-13,] # remove tank 14 because it cracked 
daily$Timepoint <- as.Date(daily$Timepoint, "%m/%d/%Y")
daily$Tank <- as.factor(daily$Tank)
daily <- subset(daily, Treatment=="Acclimation")
```

Discrete pH calculations from Tris calibrations.
```{r}
path <-("../data/pH_Tris") #set path to calibration files
file.names<-list.files(path = path, pattern = "csv$") #list all the file names in the folder to get only get the csv files
pH.cals <- data.frame(matrix(NA, nrow=length(file.names), ncol=3, dimnames=list(file.names,c("Date", "Intercept", "Slope")))) #generate a 3 column dataframe with specific column names

for(i in 1:length(file.names)) { # for every file in list start at the first and run this following function
  Calib.Data <-read.table(file.path(path,file.names[i]), header=TRUE, sep=",", na.string="NA", as.is=TRUE) #reads in the data files
  file.names[i]
  model <-lm(mVTris ~ TTris, data=Calib.Data) #runs a linear regression of mV as a function of temperature
  coe <- coef(model) #extracts the coeffecients
  summary(model)$r.squared #extracts the r squared
  plot(Calib.Data$mVTris, Calib.Data$TTris) #plots the regression data
  pH.cals[i,2:3] <- coe #inserts coefficients in the dataframe
  pH.cals[i,1] <- substr(file.names[i],1,8) #stores the file name in the Date column
}
colnames(pH.cals) <- c("Calib.Date",  "Intercept",  "Slope") #rename columns
pH.cals #view data

#constants for use in pH calculation 
R <- 8.31447215 #gas constant in J mol-1 K-1 
F <- 96485.339924 #Faraday constant in coulombs mol-1

#merge with Seawater chemistry file
SW.chem <- merge(daily, pH.cals, by="Calib.Date")
```

Calculate total pH. 
```{r}
mvTris <- SW.chem$Temperature*SW.chem$Slope+SW.chem$Intercept #calculate the mV of the tris standard using the temperature mv relationships in the measured standard curves 
STris<-35 #salinity of the Tris
phTris<- (11911.08-18.2499*STris-0.039336*STris^2)*(1/(SW.chem$Temperature+273.15))-366.27059+ 0.53993607*STris+0.00016329*STris^2+(64.52243-0.084041*STris)*log(SW.chem$Temperature+273.15)-0.11149858*(SW.chem$Temperature+273.15) #calculate the pH of the tris (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)
SW.chem$pH.Total<-phTris+(mvTris/1000-SW.chem$pH.MV/1000)/(R*(SW.chem$Temperature+273.15)*log(10)/F) #calculate the pH on the total scale (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)
```

# Plot daily measurements 
```{r}
pdf("../Output/Daily_Measurements_Acclimation.pdf")
par(mfrow=c(2,3))
plot(SW.chem$Tank, SW.chem$Temperature.C, xlab="Tank", ylab="Temperature°C", ylim = c(3.5,12), las = 2)
plot(SW.chem$Tank, SW.chem$Salinity.psu, xlab="Tank", ylab="Salinity psu", ylim = c(29,34), las = 2)
plot(SW.chem$Tank, SW.chem$pH.Total, xlab="Tank", ylab="pH Total Scale", ylim = c(8.05,8.4), las = 2)
plot(SW.chem$Tank, SW.chem$Light, xlab="Tank", ylab="Light µmol photons m^2 s^-1", ylim=c(50,150),las=2)
plot(SW.chem$Tank, SW.chem$Flow.mL.sec, xlab="Tank", ylab="Flow mL/sec", ylim=c(2,175),las=2)
dev.off()

```

# test for differences between tanks and treatments
```{r}
mod.temp <- aov(Temperature.C ~ Tank, data = SW.chem)
mod.temp
summary(mod.temp)
hist(mod.temp$residuals)

mod.sal <- aov(Salinity.psu ~ Tank, data = SW.chem)
mod.sal
summary(mod.sal)
hist(mod.sal$residuals)

mod.pH <- aov(pH.Total ~ Tank, data = SW.chem)
mod.pH
summary(mod.pH)
hist(mod.pH$residuals)

mod.light <- aov(Light ~ Tank, data = SW.chem)
mod.light
summary(mod.light)
hist(mod.light$residuals)

mod.flow <- aov(Flow.mL.sec ~ Tank, data = SW.chem)
mod.flow
summary(mod.flow)
hist(mod.flow$residuals)
```