---
title: "DailyMeasures"
author: "JAshey"
date: "2/2/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(tidyverse)
library(gridExtra)
```

# Check working directory
```{r}
getwd() 
```

# Load data
```{r}
# Load data
daily <- read.csv("data/DailyMeasurements.csv", header = T)
daily <- daily[-13,] # remove tank 14 because it cracked 
daily$Timepoint <- as.Date(daily$Timepoint, "%m/%d/%Y")
daily$Tank <- as.factor(daily$Tank)
daily <- subset(daily, Treatment=="Heat" | Treatment=="Ambient")
```

# Discrete pH calculations from Tris calibrations.
```{r}
path <-("data/pH_Tris") #set path to calibration files
file.names<-list.files(path = path, pattern = "csv$") #list all the file names in the folder to get only get the csv files
pH.cals <- data.frame(matrix(NA, nrow=length(file.names), ncol=3, dimnames=list(file.names,c("Date", "Intercept", "Slope")))) #generate a 3 column dataframe with specific column names

for(i in 1:length(file.names)) { # for every file in list start at the first and run this following function
  Calib.Data <-read.table(file.path(path,file.names[i]), header=TRUE, sep=",", na.string="NA", as.is=TRUE) #reads in the data files
  file.names[i]
  model <-lm(mVTris ~ TTris, data=Calib.Data) #runs a linear regression of mV as a function of temperature
  coe <- coef(model) #extracts the coeffecients
  summary(model)$r.squared #extracts the r squared
  plot(Calib.Data$mVTris, Calib.Data$TTris) #plots the regression data
  pH.cals[i,2:3] <- coe #inserts coefficients in the dataframe
  pH.cals[i,1] <- substr(file.names[i],1,8) #stores the file name in the Date column
}
colnames(pH.cals) <- c("Calib.Date",  "Intercept",  "Slope") #rename columns
pH.cals #view data

#constants for use in pH calculation 
R <- 8.31447215 #gas constant in J mol-1 K-1 
F <- 96485.339924 #Faraday constant in coulombs mol-1

#merge with Seawater chemistry file
SW.chem <- merge(daily, pH.cals, by="Calib.Date")
```

# Calculate total pH. 
```{r}
mvTris <- SW.chem$Temperature*SW.chem$Slope+SW.chem$Intercept #calculate the mV of the tris standard using the temperature mv relationships in the measured standard curves 
STris<-35 #salinity of the Tris
phTris<- (11911.08-18.2499*STris-0.039336*STris^2)*(1/(SW.chem$Temperature+273.15))-366.27059+ 0.53993607*STris+0.00016329*STris^2+(64.52243-0.084041*STris)*log(SW.chem$Temperature+273.15)-0.11149858*(SW.chem$Temperature+273.15) #calculate the pH of the tris (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)
SW.chem$pH.Total<-phTris+(mvTris/1000-SW.chem$pH.MV/1000)/(R*(SW.chem$Temperature+273.15)*log(10)/F) #calculate the pH on the total scale (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)
```

# Plot daily measurements 
```{r}
# By Treatment
temp.trt = ggplot(SW.chem, aes(x=Treatment, y=Temperature.C)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Temperature°C") +
  theme(axis.text.x = element_text(angle = 90))
temp.trt
sal.trt = ggplot(SW.chem, aes(x=Treatment, y=Salinity.psu)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Salinity.psu") +
    theme(axis.text.x = element_text(angle = 90))
sal.trt
pH.trt = ggplot(SW.chem, aes(x=Treatment, y=pH.Total)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("pH Total Scale") +
  theme(axis.text.x = element_text(angle = 90))
pH.trt
light.trt = ggplot(SW.chem, aes(x=Treatment, y=Light)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Light µmol photons m^2 s^-1") +
    theme(axis.text.x = element_text(angle = 90))
light.trt
flow.trt = ggplot(SW.chem, aes(x=Treatment, y=Flow.mL.sec)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Flow mL/sec") +
    theme(axis.text.x = element_text(angle = 90))
flow.trt
plot.trt <- grid.arrange(temp.trt, sal.trt, pH.trt, light.trt, flow.trt, ncol=3, nrow = 2, clip="off")
ggsave("output/Daily_Measurements.By.Treatment.pdf", plot.trt, width = 21, height = 21, units = c("in"))

# By Tank
temp.tank = ggplot(SW.chem, aes(x=Tank, y=Temperature.C)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Temperature°C") +
    theme(axis.text.x = element_text(angle = 90))
temp.tank
sal.tank = ggplot(SW.chem, aes(x=Tank, y=Salinity.psu)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Salinity.psu") +
    theme(axis.text.x = element_text(angle = 90))
sal.tank
pH.tank = ggplot(SW.chem, aes(x=Tank, y=pH.Total)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("pH Total Scale") +
    theme(axis.text.x = element_text(angle = 90))
pH.tank
light.tank = ggplot(SW.chem, aes(x=Tank, y=Light)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Light µmol photons m^2 s^-1") +
    theme(axis.text.x = element_text(angle = 90))
light.tank
flow.tank = ggplot(SW.chem, aes(x=Tank, y=Flow.mL.sec)) +
  geom_boxplot(aes(color = Treatment), size = 1) +
  ylab("Flow mL/sec") +
    theme(axis.text.x = element_text(angle = 90))
flow.tank
plot.tank <- grid.arrange(temp.tank, sal.tank, pH.tank, light.tank, flow.tank, ncol=3, nrow = 2, clip="off")
ggsave("output/Daily_Measurements.By.Tank.pdf", plot.tank, width = 21, height = 21, units = c("in"))
```

# test for differences between tanks and treatments
```{r}
# By Treatment
mod.temp <- aov(Temperature.C ~ Treatment, data = SW.chem)
mod.temp
summary(mod.temp)
hist(mod.temp$residuals)

mod.sal <- aov(Salinity.psu ~ Treatment, data = SW.chem)
mod.sal
summary(mod.sal)
hist(mod.sal$residuals)

mod.pH <- aov(pH.Total ~ Treatment, data = SW.chem)
mod.pH
summary(mod.pH)
hist(mod.pH$residuals)

mod.light <- aov(Light ~ Treatment, data = SW.chem)
mod.light
summary(mod.light)
hist(mod.light$residuals)

mod.flow <- aov(Flow.mL.sec ~ Treatment, data = SW.chem)
mod.flow
summary(mod.flow)
hist(mod.flow$residuals)

# By Tank
mod.temp <- aov(Temperature.C ~ Tank, data = SW.chem)
mod.temp
summary(mod.temp)
hist(mod.temp$residuals)

mod.sal <- aov(Salinity.psu ~ Tank, data = SW.chem)
mod.sal
summary(mod.sal)
hist(mod.sal$residuals)

mod.pH <- aov(pH.Total ~ Tank, data = SW.chem)
mod.pH
summary(mod.pH)
hist(mod.pH$residuals)

mod.light <- aov(Light ~ Tank, data = SW.chem)
mod.light
summary(mod.light)
hist(mod.light$residuals)

mod.flow <- aov(Flow.mL.sec ~ Tank, data = SW.chem)
mod.flow
summary(mod.flow)
hist(mod.flow$residuals)
```

# Plot by date 
```{r}
# Plot and save
# By Treatment
timepoint.trt <- ggplot(SW.chem, aes(x=Timepoint, y=Temperature.C, group=Treatment)) +
  geom_line(aes(color = Treatment), size = 1) 

# By Tank
timepoint.tank <- ggplot(SW.chem, aes(x=Timepoint, y=Temperature.C)) +
  geom_line(aes(color = Tank), size = 1) +
  scale_fill_brewer("Dark2") 

plot.timepoint <- grid.arrange(timepoint.tank, timepoint.trt, ncol=1, nrow = 2, clip="off")
ggsave("output/Daily_Measurements.By.Date.pdf", plot.tank, width = 21, height = 25, units = c("in"))
```




