---
title: "ACER_k2 gff_UTR_extension"
author: "Javier Rodriguez Casariego"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir ='/Volumes/JARC_2T/Other_Projects/CSHORE/CSHORE_crossprime/GFFcorrection_UTR')
```

```{bash}

GFF_FILE="/scratch/jeirinlo/jrodr979/tagseq_NOAA_serena/GFF_correction/genomic.gff" 
genome="/scratch/jeirinlo/jrodr979/tagseq_NOAA_serena/GFF_correction/GCA_032359415.1_NEU
_Acer_K2_genomic.fasta"

grep -v '^#' ${GFF_FILE} | cut -s -f 3 | sort | uniq -c | sort -rn > all_features.txt

cat all_features.txt

# extract feature types and generate individual gffs

grep $'\tmRNA\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.mRNA.gff
grep $'\tgene\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.gene.gff
grep $'\texon\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.exon.gff 
grep $'\tCDS\t'  ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.CDS.gff
grep $'\ttRNA\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.tRNA.gff
grep $'\tregion\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.region.gff
grep $'\tpseudogene\t' ${GFF_FILE} | grep -v '^NC_' > ACER_k2.GFFannotation.pseudogene.gff

cat is ${genome} | awk '$0 ~ ">" {if (NR > 1) {print c;} c=0;printf substr($0,2,100) "\t"; } $0 !~ ">" {c+=length($0);} END { print c; }' > ACER_k2.Chromosome_lenghts.txt

# extract scaffold names  	

awk -F" " '{print $1}' ACER_k2.Chromosome_lenghts.txt > ACER_k2.Chromosome-Names.txt

#Sort GFF files for downstream use

sortBed -faidx ACER_k2.Chromosome-Names.txt -i ACER_k2.GFFannotation.gene.gff > ACER_k2.GFFannotation.gene_sorted.gff
sortBed -faidx ACER_k2.Chromosome-Names.txt -i ACER_k2.GFFannotation.exon.gff > ACER_k2.GFFannotation.exon_sorted.gff
sortBed -faidx ACER_k2.Chromosome-Names.txt -i ACER_k2.GFFannotation.CDS.gff > ACER_k2.GFFannotation.CDS_sorted.gff
sortBed -faidx ACER_k2.Chromosome-Names.txt -i ACER_k2.GFFannotation.mRNA.gff > ACER_k2.GFFannotation.mRNA_sorted.gff

flankBed -i ACER_k2.GFFannotation.gene_sorted.gff -g ${genome}.fai -l 0 -r 2000 -s | awk '{gsub("gene","3prime_UTR",$3); print $0" }'| awk '{if($5-$4 > 3)print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}'| tr ' ' '\t' > ACER_k2.GFFannotation.3UTR.gff
flankBed -i ACER_k2.GFFannotation.gene_sorted.gff -g ${genome}.fai -l 2000 -r 0 -s | awk '{gsub("gene","5prime_UTR",$3); print $0 }'| awk '{if($5-$4 > 3)print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}'| tr ' ' '\t' > ACER_k2.GFFannotation.5UTR.gff

# Create longer UTR regions 3kb

flankBed -i ACER_k2.GFFannotation.gene_sorted.gff -g ${genome}.fai -l 0 -r 3000 -s | awk '{gsub("gene","3prime_UTR",$3); print $0 }'| awk '{if($5-$4 > 3)print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}'| tr ' ' '\t' > ACER_k2.GFFannotation.3UTR_3kb.gff
flankBed -i ACER_k2.GFFannotation.gene_sorted.gff -g ${genome}.fai -l 3000 -r 0 -s | awk '{gsub("gene","5prime_UTR",$3); print $0 }'| awk '{if($5-$4 > 3)print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9}'| tr ' ' '\t' > ACER_k2.GFFannotation.5UTR_3kb.gff


### Remove portions of UTR that overlap with neighboring genes

subtractBed -a ACER_k2.GFFannotation.3UTR.gff -b ACER_k2.GFFannotation.gene_sorted.gff > ACER_k2.GFFannotation.3UTR_corrected.gff 
subtractBed -a ACER_k2.GFFannotation.5UTR.gff -b ACER_k2.GFFannotation.gene_sorted.gff > ACER_k2.GFFannotation.5UTR_corrected.gff 
subtractBed -a ACER_k2.GFFannotation.3UTR_3kb.gff -b ACER_k2.GFFannotation.gene_sorted.gff > ACER_k2.GFFannotation.3UTR_3kb_corrected.gff 
subtractBed -a ACER_k2.GFFannotation.5UTR_3kb.gff -b ACER_k2.GFFannotation.gene_sorted.gff > ACER_k2.GFFannotation.5UTR_3kb_corrected.gff 
```

```{r}
library(dplyr)
library(tidyr)

## Fix gene track

gene <- read.delim("UTR_add_extend/ACER_k2.GFFannotation.gene_sorted.gff", 
           sep = "\t", header = FALSE)

three_UTR <- read.delim("UTR_add_extend/ACER_k2.GFFannotation.3UTR_3kb_corrected.gff", 
                         sep = "\t", header = FALSE)
five_UTR <- read.delim("UTR_add_extend/ACER_k2.GFFannotation.5UTR_3kb_corrected.gff", 
                        sep = "\t", header = FALSE)
mRNA <- read.delim("UTR_add_extend/ACER_k2.GFFannotation.mRNA_sorted.gff", 
                                sep = "\t", header = FALSE)

## 5' and 3'UTRs locate differently in fw and rev strands so i need to modify the gene track accordingly
gene2 <-merge(three_UTR, five_UTR, by = "V9")
gene2plus <- gene2[which(gene2$V7.x=="+"),]
gene2minus <- gene2[which(gene2$V7.x=="-"),]

head(gene2plus)
names(gene2plus)

geneplus <- gene2plus[,c(2:4,13,6:9,1)]
geneminus <- gene2minus[,c(2:5,14:17,1)]

head(geneplus)

colnames(geneminus) <- c("V1","V2","V3","V4","V5","V6","V7","V8","V9")
colnames(geneplus) <- c("V1","V2","V3","V4","V5","V6","V7","V8","V9")

gene_new <- rbind(geneplus, geneminus)                        

gene_new$V3 <- gsub("3prime_UTR", "gene", gene_new$V3)
gene_new$V3 <- gsub("5prime_UTR", "gene", gene_new$V3)

gene_new$ID <- gene_new$V9
gene_new <- separate(data = gene_new, col = ID, into = "ID", sep = ";")

gene$ID <- gene$V9
gene <- separate(data = gene, col = ID, into = "ID", sep = ";")

gene_new <- gene_new[!duplicated(gene_new$ID), ]

missing_genes <- anti_join(gene, gene_new
                           , by = c("ID"))
gene_new <- rbind(gene_new, missing_genes)

gene_new <- gene_new[,-10]

write.table(gene_new, file = "UTR_add_extend/ACER_k2.GFFannotation.gene_3UTR_3kb_extended.gff", 
            sep = "\t", row.names=FALSE, col.names=FALSE, quote=FALSE)


### Fix mRNA track
transcript <- mRNA

head(transcript)

trans_sep <- transcript
trans_sep$ID <- trans_sep$V9  
trans_sep <- separate(trans_sep, ID, c("V10", "ID"), sep = ";")
trans_sep$ID <- gsub("Parent", "ID", trans_sep$ID)

gene_sep <- gene_new
gene_sep$ID <- gene_sep$V9
gene_sep <- separate(data = gene_sep, col = ID, into = "ID", sep = ";")

trans_new <- merge(trans_sep, gene_sep, by = "ID")
trans_new <- trans_new[,c(2:4,15:16,7:11,1)]
colnames(trans_new) <- c("V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","ID")
trans_new <- trans_new[!duplicated(trans_new$V10), ]
missing_trans <- anti_join(trans_sep, trans_new, by = c("V10"))
trans_new <- rbind(trans_new, missing_trans)
trans_new <- trans_new[, -c(10:11)]
write.table(trans_new, file = "UTR_add_extend/ACER_k2.GFFannotation.mRNA_3UTR_3kb_extended.gff", 
            sep = "\t", row.names=FALSE, col.names=FALSE, quote=FALSE)

## Eliminate duplicates from 5' and 3' UTR tracks and fix attributes

five_UTR_new <- five_UTR[!duplicated(five_UTR$V9), ]
five_UTR_new$ID <- five_UTR_new$V9 
five_UTR_new <- separate(five_UTR_new, ID, c("ID"), sep = ";")
five_UTR_new$ID <- gsub("gene", "5utr", five_UTR_new$ID)
five_UTR_new$V9 <- gsub("ID=", "Parent=", five_UTR_new$V9)

five_UTR_new <- five_UTR_new %>%
  mutate(V9 = paste(ID, V9, sep = ";"))
five_UTR_new <- five_UTR_new[, -c(10)]

three_UTR_new <- three_UTR[!duplicated(three_UTR$V9), ]
three_UTR_new$ID <- three_UTR_new$V9 
three_UTR_new <- separate(three_UTR_new, ID, c("ID"), sep = ";")
three_UTR_new$ID <- gsub("gene", "3utr", three_UTR_new$ID)
three_UTR_new$V9 <- gsub("ID=", "Parent=", three_UTR_new$V9)

three_UTR_new <- three_UTR_new %>%
  mutate(V9 = paste(ID, V9, sep = ";"))
three_UTR_new <- three_UTR_new[, -c(10)]


write.table(five_UTR_new, file = "UTR_add_extend/ACER_k2.GFFannotation.5UTR_3kb_uniq.gff", 
            sep = "\t", row.names=FALSE, col.names=FALSE, quote=FALSE)
write.table(three_UTR_new, file = "UTR_add_extend/ACER_k2.GFFannotation.3UTR_3kb_uniq.gff", 
            sep = "\t", row.names=FALSE, col.names=FALSE, quote=FALSE)
```

```{bash}
# Create new gff file

cd /Volumes/JARC_2T/Other_Projects/CSHORE/CSHORE_crossprime/GFFcorrection_UTR

cat \
ACER_k2.GFFannotation.exon.gff \
ACER_k2.GFFannotation.CDS.gff \
ACER_k2.GFFannotation.mRNA_3UTR_3kb_extended.gff \
ACER_k2.GFFannotation.gene_3UTR_3kb_extended.gff \
ACER_k2.GFFannotation.region.gff \
ACER_k2.GFFannotation.tRNA.gff \
ACER_k2.GFFannotation.pseudogene.gff \
| sortBed -i - \
| uniq \
> ../ACER_k2.genomic.UTRextended.gff

#gffread -F -w ACER_k2_UTRExt_gff_trans.fa -g ${genome} ACER_k2.genomic.UTRextended_JARC.gff
```


