---
title: "Temperature"
author: "HM Putnam"
date: "1/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Install and Load necessary libraries
if("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 

library(lubridate)
library(tidyverse)
library(emmeans)
library(gridExtra)
```

## Acclimation Temperature
### Insert timeframe here

```{r }
##### CONTINUOUS TEMPERATURE DATA FROM HOBO LOGGERS #####

##### QC Hobo Files #####

#Timeframe
#data/Hobo/temp_logger/20210405

# Read in temp data 
Tank1 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank1_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank2 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank2_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank2 <- Tank2[1:nrow(Tank1),]
Tank3 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank3_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank3 <- Tank3[1:nrow(Tank1),]
Tank4 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank4_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank4 <- Tank4[1:nrow(Tank1),]
Tank5 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank5_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank5 <- Tank5[1:nrow(Tank1),]
Tank6 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank6_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank6 <- Tank6[1:nrow(Tank1),]
Tank7 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank7_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank7 <- Tank7[1:nrow(Tank1),]
Tank8 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank8_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank8 <- Tank8[1:nrow(Tank1),]
Tank9 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank9_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank9 <- Tank9[1:nrow(Tank1),]
Tank10 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank10_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank10 <- Tank10[1:nrow(Tank1),]
Tank11 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank11_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank11 <- Tank11[1:nrow(Tank1),]
Tank12 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank12_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank12 <- Tank12[1:nrow(Tank1),]
Tank15 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank15_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank15 <- Tank15[1:nrow(Tank1),]
Tank16 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank16_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank16 <- Tank16[1:nrow(Tank1),]
Tank17 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank17_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank17 <- Tank17[1:nrow(Tank1),]
Tank18 <- read.csv("data/Hobo/temp_light_logger/20210419/Tank18_20210419.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,1:3]
Tank18 <- Tank18[1:nrow(Tank1),]
Tank1$Tank <- "Tank1"
Tank2$Tank <- "Tank2"
Tank3$Tank <- "Tank3"
Tank4$Tank <- "Tank4"
Tank5$Tank <- "Tank5"
Tank6$Tank <- "Tank6"
Tank7$Tank <- "Tank7"
Tank8$Tank <- "Tank8"
Tank9$Tank <- "Tank9"
Tank10$Tank <- "Tank10"
Tank11$Tank <- "Tank11"
Tank12$Tank <- "Tank12"
Tank15$Tank <- "Tank15"
Tank16$Tank <- "Tank16"
Tank17$Tank <- "Tank17"
Tank18$Tank <- "Tank18"

Tank1$Treatment <- "Ambient"
Tank2$Treatment <- "Ambient"
Tank3$Treatment <- "High"
Tank4$Treatment <- "High"
Tank5$Treatment <- "Ambient"
Tank6$Treatment <- "High"
Tank7$Treatment <- "High"
Tank8$Treatment <- "Ambient"
Tank9$Treatment <- "High"
Tank10$Treatment <- "Ambient"
Tank11$Treatment <- "High"
Tank12$Treatment <- "Ambient"
Tank15$Treatment <- "High"
Tank16$Treatment <- "Ambient"
Tank17$Treatment <- "High"
Tank18$Treatment <- "Ambient"


data <- rbind(Tank1, Tank2, Tank3, Tank4, Tank5, Tank6,
              Tank7, Tank8, Tank9, Tank10, Tank11,
              Tank12, Tank15, Tank16, Tank17, Tank18)

colnames(data) <- c("Date.Time", "Temp", "Light", "Tank", "Treatment")
data$Date.Time <- parse_date_time(data$Date.Time, "%Y-%m-%d %H:%M:%S", tz = "EST")

write.csv(data,file="output/All_Tank_HoboTempLight_data.csv")

Temps <- data %>% ggplot(aes(x=Date.Time, y=Temp)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
Temps
ggsave("output/All_Tank_HoboTemp.pdf", plot = last_plot(), width = 8, height = 4)

#remove commas from light data and make numeric
data$Light <- as.numeric(gsub(",", "", data$Light))

Light <- data %>% ggplot(aes(x=Date.Time, y=Light)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Light lux")
ggsave("output/All_Tank_HoboLight.pdf", plot = last_plot(), width = 8, height = 4)

```

```{r}
# Looking at April
test <- temp.data[c(122481:133168),]
Temps_Apr <- ggplot(test, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Tank), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
Temps_Apr
```


```{r }
# # Read in tide data 
# tides <- read.csv("data/tide.csv", sep=",", header=TRUE, na.strings = "NA")
# tides$Date.Time <- paste(tides$Date, tides$Time.LST, sep = " ")
# tides$Date.Time <- parse_date_time(tides$Date.Time, "%m/%d/%y %H:%M", tz = "EST")
# tides$Prelim.m <- as.numeric(as.character(tides$Prelim.m))
# tides <- tides[191:2531,]
# 
# tides.fig <- ggplot(tides, aes(x=Date.Time, y=Prelim.m)) +
#   geom_line()+
#   ylim(0,2)+
#   ylab("Tidal Height m")
# ggsave("output/Tidalcycle.pdf", plot = last_plot(), width = 8, height = 4)
# 
# 
# temperatureColor <- "red"
# priceColor <- "black"
# 
# ggplot() +
# geom_line(data=data, aes(x=Date.Time, y=Tank1), color='red') + 
# geom_line(data=tides, aes(x=Date.Time, y=Prelim.m), color='black')+
#   scale_y_continuous(
#     # Features of the first axis
#     name = "Temperature (°C)",
#     # Add a second axis and specify its features
#     sec.axis = sec_axis(~., name="Tidal Height (m)")) + 
#   theme(
#     axis.title.y = element_text(color = temperatureColor, size=13),
#     axis.title.y.right = element_text(color = priceColor, size=13)
#   )
# ggsave("output/Tank_Temps_Tides.pdf", plot = last_plot(), width = 8, height = 4)

```
