---
title: "Temperature"
author: "HM Putnam"
date: "1/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Install and Load necessary libraries
if("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 

library(lubridate)
library(tidyverse)
library(emmeans)
library(gridExtra)
```

##  
### Insert timeframe here

```{r }
##### CONTINUOUS TEMPERATURE DATA FROM HOBO LOGGERS #####


##### QC Acclimation Hobo Files #####

#Timeframe
#data/Hobo/temp_light_logger/20210206

# Read in temp data 
Tank1 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank1_21002975.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank2 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank2_21002981.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank2 <- Tank2[1:nrow(Tank1),]
Tank3 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank3_21002972.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank3 <- Tank3[1:nrow(Tank1),]
Tank4 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank4_21002974.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank4 <- Tank4[1:nrow(Tank1),]
Tank5 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank5_21002982.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank5 <- Tank5[1:nrow(Tank1),]
Tank6 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank6_21002973.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank6 <- Tank6[1:nrow(Tank1),]
Tank7 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank7_20937873.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank7 <- Tank7[1:nrow(Tank1),]
Tank8 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank8_21002979.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank8 <- Tank8[1:nrow(Tank1),]
Tank9 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank9_21002977.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank9 <- Tank9[1:nrow(Tank1),]
Tank10 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank10_21002978.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank10 <- Tank10[1:nrow(Tank1),]
Tank11 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank11_21002980.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank11 <- Tank11[1:nrow(Tank1),]
Tank12 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank12_21002976.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank12 <- Tank12[1:nrow(Tank1),]
Tank15 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank15_20937869.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank15 <- Tank15[1:nrow(Tank1),]
Tank16 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank16_20937870.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank16 <- Tank16[1:nrow(Tank1),]
Tank17 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank17_20937871.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank17 <- Tank17[1:nrow(Tank1),]
Tank18 <- read.csv("data/Hobo/temp_light_logger/20210206/20210206_Tank18_20937872.csv", sep=",", skip=c(2), header=FALSE, na.strings = "NA")[ ,2:4]
Tank18 <- Tank18[1:nrow(Tank1),]

data <- cbind(Tank1, Tank2$V3, Tank3$V3, Tank4$V3, Tank5$V3, Tank6$V3,
              Tank7$V3, Tank8$V3, Tank9$V3, Tank10$V3, Tank11$V3,
              Tank12$V3, Tank15$V3, Tank16$V3, Tank17$V3, Tank18$V3)
colnames(data) <- c("Date.Time", "Tank1","Tank2", "Tank3", "Tank4", "Tank5", "Tank6",
                    "Tank7","Tank8", "Tank9", "Tank10", "Tank11", "Tank12",
                    "Tank15", "Tank16", "Tank17", "Tank18")
data$Date.Time <- parse_date_time(data$Date.Time, "%m/%d/%y %I:%M:%S %p", tz = "EST")
data$Date.Time <- data$Date.Time + hours(5) # add x hours
#data <- data[13:nrow(data)-6,]
#Save acclimation data to file
temp.data <- data
write.csv(temp.data,file="output/All_Tank_HoboTempLight_data.csv")

#Convert to Long
temp.acc.data <- pivot_longer(temp.data, cols = Tank1:Tank18, names_to="Tank" )

Acc.Temps <- ggplot(temp.acc.data, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Tank), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/All_Tank_HoboTempLight.pdf", plot = last_plot(), width = 8, height = 4)

```

```{r }
# # Read in tide data 
# tides <- read.csv("data/tide.csv", sep=",", header=TRUE, na.strings = "NA")
# tides$Date.Time <- paste(tides$Date, tides$Time.LST, sep = " ")
# tides$Date.Time <- parse_date_time(tides$Date.Time, "%m/%d/%y %H:%M", tz = "EST")
# tides$Prelim.m <- as.numeric(as.character(tides$Prelim.m))
# tides <- tides[191:2531,]
# 
# tides.fig <- ggplot(tides, aes(x=Date.Time, y=Prelim.m)) +
#   geom_line()+
#   ylim(0,2)+
#   ylab("Tidal Height m")
# ggsave("output/Tidalcycle.pdf", plot = last_plot(), width = 8, height = 4)
# 
# 
# temperatureColor <- "red"
# priceColor <- "black"
# 
# ggplot() +
# geom_line(data=data, aes(x=Date.Time, y=Tank1), color='red') + 
# geom_line(data=tides, aes(x=Date.Time, y=Prelim.m), color='black')+
#   scale_y_continuous(
#     # Features of the first axis
#     name = "Temperature (°C)",
#     # Add a second axis and specify its features
#     sec.axis = sec_axis(~., name="Tidal Height (m)")) + 
#   theme(
#     axis.title.y = element_text(color = temperatureColor, size=13),
#     axis.title.y.right = element_text(color = priceColor, size=13)
#   )
# ggsave("output/Tank_Temps_Tides.pdf", plot = last_plot(), width = 8, height = 4)

```
