---
title: "Temperature"
author: "HM Putnam"
date: "1/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Install and Load necessary libraries
if("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 

library(lubridate)
library(tidyverse)
library(emmeans)
library(gridExtra)
```

```{r}
getwd()
```


##  
### Insert timeframe here

```{r }
##### CONTINUOUS TEMPERATURE & LIGHT DATA FROM HOBO LOGGERS #####

##### QC Treatment Hobo Files #####

# Some loggers were stopped and restarted at different times. Because of this, each tank's data needs to be read in and merged with the tank's data before it 

# Read in data 

#my.data <- read.csv("output/Hobo/temp_light_logger/All_Tank_HoboTempLight_data.csv", header = T)[,2:34]

# Tank1
Tank1 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank1_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 2/6/21 onward
colnames(Tank1) <- c("Date", "Temperature", "Light")
Tank1$Date <- parse_date_time(Tank1$Date, "mdyHMS", tz = "EST")
# Tank2
Tank2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank2_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 2/6/21 onward
#Tank2 <- Tank2[1:nrow(Tank1),]
colnames(Tank2) <- c("Date", "Temperature", "Light")
Tank2$Date <- parse_date_time(Tank2$Date, "mdyHMS", tz = "EST")
all <- merge(Tank1, Tank2, by = "Date", all = T)
colnames(all) <- c("Date", "Tank1_Temp", "Tank1_Light", "Tank2_Temp", "Tank2_Light")
# Tank3
Tank3 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank3_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 2/6/21 onward
#Tank3 <- Tank3[1:nrow(Tank1),]
colnames(Tank3) <- c("Date", "Temperature", "Light")
Tank3$Date <- parse_date_time(Tank3$Date, "mdyHMS", tz = "EST")
all <- merge(all, Tank3, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank3_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank3_Light'
# Tank4
Tank4 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank4_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 2/6/21 onward
#Tank3 <- Tank3[1:nrow(Tank1),]
colnames(Tank4) <- c("Date", "Temperature", "Light")
Tank4$Date <- parse_date_time(Tank4$Date, "mdyHMS", tz = "EST")
all <- merge(all, Tank4, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank4_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank4_Light'
# Tank5
Tank5.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank5_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank5.1) <- c("Date", "Temperature", "Light")
Tank5.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank5_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank5.2) <- c("Date", "Temperature", "Light")
Tank5.full <- rbind(Tank5.1, Tank5.2) # bind data from Tank 5 together
Tank5.full <- Tank5.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank5.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank5_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank5_Light'
# Tank6
Tank6.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank6_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank6.1) <- c("Date", "Temperature", "Light")
Tank6.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank6_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank6.2) <- c("Date", "Temperature", "Light")
Tank6.full <- rbind(Tank6.1, Tank6.2) # bind data from Tank 5 together
Tank6.full <- Tank6.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank6.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank6_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank6_Light'
# Tank7
Tank7.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank7_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank7.1) <- c("Date", "Temperature", "Light")
Tank7.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank7_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank7.2) <- c("Date", "Temperature", "Light")
Tank7.full <- rbind(Tank7.1, Tank7.2) # bind data from Tank 5 together
Tank7.full <- Tank7.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank7.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank7_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank7_Light'
# Tank8
Tank8.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank8_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank8.1) <- c("Date", "Temperature", "Light")
Tank8.2 <- read.csv("data/Hobo/temp_light_logger/20210512/Tank8_20210512.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 4/30/21 to 5/12/21
colnames(Tank8.2) <- c("Date", "Temperature", "Light")
Tank8.2.early <- Tank8.2[1:6951,] 
Tank8.2.early = Tank8.2.early[seq(1, nrow(Tank8.2.early), 10), ] # selecting every 10th row because logger was set to log every minute instead of every 10 mins during this period
Tank8.2.late <- Tank8.2[6963:17210,] # had to make separate df because the data here did not follow the 10th row pattern
Tank8.2.late = Tank8.2.late[seq(1, nrow(Tank8.2.late), 10), ] # selecting every 10th row because logger was set to log every minute instead of every 10 mins during this period
colnames(Tank8.2.late) <- c("Date", "Temperature", "Light")
Tank8.2 <- rbind(Tank8.2.early, Tank8.2.late)
### missing data from 5/12/21 to 5/15/21
Tank8.3 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank8_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 5/15/21 onward
colnames(Tank8.3) <- c("Date", "Temperature", "Light")
Tank8.full <- rbind(Tank8.1, Tank8.2, Tank8.3) # bind data from Tank 5 together
Tank8.full <- Tank8.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank8.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank8_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank8_Light'
# Tank9
Tank9.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank9_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank9.1) <- c("Date", "Temperature", "Light")
Tank9.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank9_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank9.2) <- c("Date", "Temperature", "Light")
Tank9.full <- rbind(Tank9.1, Tank9.2) # bind data from Tank 5 together
Tank9.full <- Tank9.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank9.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank9_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank9_Light'
# Tank10
Tank10.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank10_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank10.1) <- c("Date", "Temperature", "Light")
Tank10.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank10_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank10.2) <- c("Date", "Temperature", "Light")
Tank10.full <- rbind(Tank10.1, Tank10.2) # bind data from Tank 5 together
Tank10.full <- Tank10.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank10.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank10_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank10_Light'
# Tank11
Tank11.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank11_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank11.1) <- c("Date", "Temperature", "Light")
Tank11.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank11_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank11.2) <- c("Date", "Temperature", "Light")
Tank11.full <- rbind(Tank11.1, Tank11.2) # bind data from Tank 5 together
Tank11.full <- Tank11.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank11.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank11_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank11_Light'
# Tank12
Tank12.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank12_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank12.1) <- c("Date", "Temperature", "Light")
Tank12.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank12_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank12.2) <- c("Date", "Temperature", "Light")
Tank12.full <- rbind(Tank12.1, Tank12.2) # bind data from Tank 5 together
Tank12.full <- Tank12.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank12.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank12_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank12_Light'
# Tank15
Tank15.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank15_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank15.1) <- c("Date", "Temperature", "Light")
Tank15.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank15_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank15.2) <- c("Date", "Temperature", "Light")
Tank15.full <- rbind(Tank15.1, Tank15.2) # bind data from Tank 15 together
Tank15.full <- Tank15.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank15.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank15_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank15_Light'
# Tank16
Tank16.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank16_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank16.1) <- c("Date", "Temperature", "Light")
Tank16.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank16_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank16.2) <- c("Date", "Temperature", "Light")
Tank16.full <- rbind(Tank16.1, Tank16.2) # bind data from Tank 5 together
Tank16.full <- Tank16.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank16.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank16_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank16_Light'
# Tank17
Tank17.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank17_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank17.1) <- c("Date", "Temperature", "Light")
Tank17.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank17_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank17.2) <- c("Date", "Temperature", "Light")
Tank17.full <- rbind(Tank17.1, Tank17.2) # bind data from Tank 5 together
Tank17.full <- Tank17.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank17.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank17_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank17_Light'
# Tank18
Tank18.1 <- read.csv("data/Hobo/temp_light_logger/20210430/Tank18_20210430.csv", sep=",", skip = c(2), header=T, na.strings = "NA")[ ,1:3] # data from 2/6/21 to 4/30/21
colnames(Tank18.1) <- c("Date", "Temperature", "Light")
Tank18.2 <- read.csv("data/Hobo/temp_light_logger/20210718/Tank17_20210718.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 4/30/21 onward
colnames(Tank18.2) <- c("Date", "Temperature", "Light")
Tank18.full <- rbind(Tank18.1, Tank18.2) # bind data from Tank 5 together
Tank18.full <- Tank18.full %>% 
  mutate(Date = parse_date_time(Date, orders = c('ymdHMS', "mdyHMS"), tz = "EST"))
all <- merge(all, Tank18.full, by = "Date", all = T)
colnames(all)[colnames(all) == 'Temperature'] <- 'Tank18_Temp'
colnames(all)[colnames(all) == 'Light'] <- 'Tank18_Light'


#all <- na.omit(all)
#all$Date <- parse_date_time(data$Date, "Ymd HMS", tz = "EST")
all$Date <- all$Date + hours(5) # add x hours
#data <- data[13:nrow(data)-6,]
#Save data to file
write.csv(all,file="output/Hobo/temp_light_logger/All_Tank_HoboTempLight_data.csv")
```


```{r }
# Select only temperature 
temp.data <- all[,c("Date", 
                     "Tank1_Temp", 
                     "Tank2_Temp", 
                     "Tank3_Temp",
                     "Tank4_Temp",
                     "Tank5_Temp", 
                     "Tank6_Temp", 
                     "Tank7_Temp",
                     "Tank8_Temp",
                     "Tank9_Temp",
                     "Tank10_Temp", 
                     "Tank11_Temp", 
                     "Tank12_Temp", 
                     "Tank15_Temp",
                     "Tank16_Temp", 
                     "Tank17_Temp", 
                     "Tank18_Temp")]

# Rename columns
colnames(temp.data) <- c("Date.Time", 
                     "Tank1", 
                     "Tank2", 
                     "Tank3",
                     "Tank4",
                     "Tank5", 
                     "Tank6", 
                     "Tank7",
                     "Tank8",
                     "Tank9",
                     "Tank10", 
                     "Tank11", 
                     "Tank12", 
                     "Tank15",
                     "Tank16", 
                     "Tank17", 
                     "Tank18")

# Convert to Long
temp.trt.data <- pivot_longer(temp.data, cols = Tank1:Tank18, names_to="Tank" )

# Assign treatment to each tank
temp.trt.data <- temp.trt.data %>% 
  mutate(Treatment = case_when(
    Tank == "Tank1" ~ "Ambient",
    Tank == "Tank2" ~ "Ambient",
    Tank == "Tank3" ~ "Heat",
    Tank == "Tank4" ~ "Heat",
    Tank == "Tank5" ~ "Ambient",
    Tank == "Tank6" ~ "Heat",
    Tank == "Tank7" ~ "Heat",
    Tank == "Tank8" ~ "Ambient",
    Tank == "Tank9" ~ "Heat",
    Tank == "Tank10" ~ "Ambient",
    Tank == "Tank11" ~ "Heat",
    Tank == "Tank12" ~ "Ambient",
    Tank == "Tank15" ~ "Heat",
    Tank == "Tank16" ~ "Ambient",
    Tank == "Tank17" ~ "Heat",
    Tank == "Tank18" ~ "Ambient"))

## Need to remove times when logger was out of water

# Plot and save 
ggplot(temp.trt.data, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/Hobo/temp_light_logger/All_Tank_HoboTemp_Treatment.pdf", plot = last_plot(), width = 8, height = 4)


## Filter by June temps
may.june.temp <- temp.trt.data %>% filter(Date.Time >= "2021-05-01 00:00:00")

# Plot and save June temps 
ggplot(may.june.temp, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/Hobo/temp_light_logger/May.June_HoboTemp_Treatment.pdf", plot = last_plot(), width = 8, height = 4)

```


```{r }
# Select only light 
light.data <- all[,c("Date", 
                     "Tank1_Light", 
                     "Tank2_Light", 
                     "Tank3_Light",
                     "Tank4_Light",
                     "Tank5_Light", 
                     "Tank6_Light", 
                     "Tank7_Light",
                     "Tank8_Light",
                     "Tank9_Light",
                     "Tank10_Light", 
                     "Tank11_Light", 
                     "Tank12_Light", 
                     "Tank15_Light",
                     "Tank16_Light", 
                     "Tank17_Light", 
                     "Tank18_Light")]

# Removing commas in columns with light data (not Date column!!)
clean <- function(ttt){
  as.numeric( gsub('[^a-zA-Z0-9.]', '', ttt))
}
light.data[,2:17] <- sapply(light.data[,2:17], clean)

colnames(light.data) <- c("Date.Time", 
                     "Tank1", 
                     "Tank2", 
                     "Tank3",
                     "Tank4",
                     "Tank5", 
                     "Tank6", 
                     "Tank7",
                     "Tank8",
                     "Tank9",
                     "Tank10", 
                     "Tank11", 
                     "Tank12", 
                     "Tank15",
                     "Tank16", 
                     "Tank17", 
                     "Tank18")

# Convert to Long
light.trt.data <- pivot_longer(light.data, cols = Tank1:Tank18, names_to="Tank" )

# Assign treatment to each tank
light.trt.data <- light.trt.data %>% 
  mutate(Treatment = case_when(
    Tank == "Tank1" ~ "Ambient",
    Tank == "Tank2" ~ "Ambient",
    Tank == "Tank3" ~ "Heat",
    Tank == "Tank4" ~ "Heat",
    Tank == "Tank5" ~ "Ambient",
    Tank == "Tank6" ~ "Heat",
    Tank == "Tank7" ~ "Heat",
    Tank == "Tank8" ~ "Ambient",
    Tank == "Tank9" ~ "Heat",
    Tank == "Tank10" ~ "Ambient",
    Tank == "Tank11" ~ "Heat",
    Tank == "Tank12" ~ "Ambient",
    Tank == "Tank15" ~ "Heat",
    Tank == "Tank16" ~ "Ambient",
    Tank == "Tank17" ~ "Heat",
    Tank == "Tank18" ~ "Ambient"))

## Need to remove times when logger was out of water

# Plot and save 
ggplot(light.trt.data, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Light (lux)")
ggsave("output/Hobo/temp_light_logger/All_Tank_HoboLight_Treatment.pdf", plot = last_plot(), width = 8, height = 4)

## Filter by June temps
may.june.light <- light.trt.data %>% filter(Date.Time >= "2021-05-01 00:00:00")

# Plot and save June temps 
ggplot(may.june.light, aes(x=Date.Time, y=value)) +
  geom_line(aes(color = Treatment), size = 1)+
  #ylim(5,15)+
  ylab("Light (lux)")
ggsave("output/Hobo/temp_light_logger/May.June_HoboTemp_Treatment.pdf", plot = last_plot(), width = 8, height = 4)

```

