---
title: "Outdoor Tank Temperature"
author: "jillashey"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages 
```{r}
#Install and Load necessary libraries
if("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 

library(lubridate)
library(tidyverse)
library(emmeans)
library(gridExtra)
```

# Check working directory
```{r}
getwd()
```

# Read in data 
```{r}
outdoor <- read.csv("data/Hobo/temp_light_logger/Outdoor/OutdoorTank_20210620.csv", sep=",", header=T, na.strings = "NA")[ ,2:4] # data from 20201221 onward
colnames(outdoor) <- c("Date.Time", "Temperature", "Light")
outdoor$Date.Time <- parse_date_time(outdoor$Date.Time, "mdyHMS", tz = "EST")
```

# Plot data
```{r}
# Plot temperature data
ggplot(outdoor, aes(x=Date.Time, y=Temperature)) +
  geom_line(size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/Hobo/temp_light_logger/OutdoorTank_HoboTemp.pdf", plot = last_plot(), width = 8, height = 4)

# Plot light data
ggplot(outdoor, aes(x=Date.Time, y=Light)) +
  geom_line(size = 1)+
  #ylim(5,15)+
  ylab("Light")
ggsave("output/Hobo/temp_light_logger/OutdoorTank_HoboLight.pdf", plot = last_plot(), width = 8, height = 4)
```

# Plot June data (time when outdoor corals for AB were collected)
```{r}
# Filter by June dates
june.temp <- outdoor %>% filter(Date.Time >= "2021-06-01 00:00:00")

# Plot June temperature data
ggplot(june.temp, aes(x=Date.Time, y=Temperature)) +
  geom_line(size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
ggsave("output/Hobo/temp_light_logger/OutdoorTank_HoboTemp.June.pdf", plot = last_plot(), width = 8, height = 4)

# Plot June light data 
ggplot(june.temp, aes(x=Date.Time, y=Light)) +
  geom_line(size = 1)+
  #ylim(5,15)+
  ylab("Light")
ggsave("output/Hobo/temp_light_logger/OutdoorTank_HoboLight.June.pdf", plot = last_plot(), width = 8, height = 4)
```