---
title: "Squarical Temperatures"
author: "jillashey"
date: "7/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install and Load necessary libraries
```{r}
if("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if("emmeans" %in% rownames(installed.packages()) == 'FALSE') install.packages('emmeans') 
if("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 

library(lubridate)
library(tidyverse)
library(emmeans)
library(gridExtra)
```

# Read in data 
```{r}
##### CONTINUOUS TEMPERATURE & LIGHT DATA FROM HOBO LOGGERS #####
sq1 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical1_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
colnames(sq1) <- c("Date.Time", "Temperature")
sq2 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical2_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq2 <- sq2[1:nrow(sq1),]
colnames(sq2) <- c("Date.Time", "Temperature")
sq3 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical3_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq3 <- sq3[1:nrow(sq1),]
colnames(sq3) <- c("Date.Time", "Temperature")
sq4 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical4_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq4 <- sq4[1:nrow(sq1),]
colnames(sq4) <- c("Date.Time", "Temperature")
sq5 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical5_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq5 <- sq5[1:nrow(sq1),]
colnames(sq5) <- c("Date.Time", "Temperature")
sq6 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical6_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq6 <- sq6[1:nrow(sq1),]
colnames(sq6) <- c("Date.Time", "Temperature")
sq7 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical7_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq7 <- sq7[1:nrow(sq1),]
colnames(sq7) <- c("Date.Time", "Temperature")
sq8 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical8_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq8 <- sq8[1:nrow(sq1),]
colnames(sq8) <- c("Date.Time", "Temperature")
sq9 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical9_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq9 <- sq9[1:nrow(sq1),]
colnames(sq9) <- c("Date.Time", "Temperature")
sq10 <- read.csv("data/Hobo/temp_logger/20210731_Squarical/squarical10_20210731.csv", sep=",", skip=c(3), header=FALSE, na.strings = "NA")[ ,2:3]
sq10 <- sq10[1:nrow(sq1),]
colnames(sq10) <- c("Date.Time", "Temperature")

# Assign squarical numbers and for each df 
sq1$Squarical <- "Squarical1"
sq2$Squarical <- "Squarical2"
sq3$Squarical <- "Squarical3"
sq4$Squarical <- "Squarical4"
sq5$Squarical <- "Squarical5"
sq6$Squarical <- "Squarical6"
sq7$Squarical <- "Squarical7"
sq8$Squarical <- "Squarical8"
sq9$Squarical <- "Squarical9"
sq10$Squarical <- "Squarical10"

sq1$ParentTreatment <- "Heat"
sq2$ParentTreatment <- "Ambient"
sq3$ParentTreatment <- "Heat"
sq4$ParentTreatment <- "Ambient"
sq5$ParentTreatment <- "Ambient"
sq6$ParentTreatment <- "Ambient"
sq7$ParentTreatment <- "Heat"
sq8$ParentTreatment <- "Heat"
sq9$ParentTreatment <- "Heat"
sq10$ParentTreatment <- "Ambient"
```


# Bind and save data 
```{r}
data <- rbind(sq1, sq2, sq3, sq4, sq5, sq6, sq7, sq8, sq9, sq10)
#colnames(data) <- c("Date.Time", "Temperature", "Squarical", "ParentTreatment")
data$Date.Time <- strptime(data$Date.Time, "%m/%d/%y %I:%M:%S %p")

write.csv(data,file="output/Hobo/temp_logger/Squarical_HoboTemp.csv")
```

# Plot data 
```{r}
Temps <- data %>% ggplot(aes(x=Date.Time, y=Temperature)) +
  geom_line(aes(color = Squarical), size = 1)+
  #ylim(5,15)+
  ylab("Temperature °C")
Temps









ggsave("output/Hobo/temp_logger/Squarical_HoboTemp.pdf", plot = last_plot(), width = 8, height = 4)
```


